### ISSUE TITLE
lang pair downloader needs crash recovery

### ISSUE THREAD

**Issue by bruceleerabbit** [argosopentech/argos-translate-gui#3]
When using the GUI to fetch a new language pair, the process crashed out of the pure blue without reason.  The GUI window disappeared, and the terminal showed a dump of how many bytes were fetched and how many were not.  It did not say why it crashed, but after eating up ~80mb of a measured rate service I was stuffed.  I switched to the CLI method (`argospm`) in hopes of getting more verbosity. I got zero verbosity and not only that but it started over from the beginning.  It should have already had ~99% of the file.

Apparently the GUI downloader uses different code than `argospm` (as they are storing the data in different locations).  So the GUI and `argospm` both need a crash recovery mechanism.  This bug report is for the GUI downloader.

**Comment by PJ-Finlay** [comment]
This was fixed in Argos Translate 1.7
